<?php 
require_once 'PHPExcel.php';  
require_once 'PHPExcel/Writer/Excel5.php';    // 用于其他低版本xls  
include("quote.php");  
///////////////////
$startTime=$_REQUEST['start'];
$endTime=$_REQUEST['end'];
//$startTime="2012-9-10 11:11:11";
//$endTime="2012-12-10 11:11:11";
$db=openSQLite3Sales() or die(ERR_CONNECT_DB);
$unixtime=strtotime($startTime);
$startTime=date("Y-m-d H:i:s",$unixtime);
$unixtime=strtotime($endTime);
$endTime=date("Y-m-d H:i:s",$unixtime);
$sql="select sum(price*quantity) from sales_data  where DATETIME(timestamp)>='".$startTime."' and DATETIME(timestamp)<='".$endTime."'";
$sql1="select dish_id,sum(price*quantity),sum(quantity) from sales_data where DATETIME(timestamp)>='".$startTime."' and DATETIME(timestamp)<='".$endTime."' group by dish_id";
$rs=$db->query($sql) or die(ERR_SELECT_DB);
$row=$rs->fetchArray();
$total=$row['sum(price*quantity)'];
$rs=$db->query($sql1) or die(ERR_SELECT_DB);
$db=openSQLite3Dish() or die(ERR_CONNECT_DB);
//////////////////////////////////////////////
$objExcel = new PHPExcel();  
$objWriter = new PHPExcel_Writer_Excel5($objExcel);    // 用于其他版本格式  
$objProps = $objExcel->getProperties();  
$objProps->setCreator("Zeal Li");  
$objProps->setLastModifiedBy("Zeal Li");  
$objProps->setTitle("Office XLS Test Document");  
$objProps->setSubject("Office XLS Test Document, Demo");  
$objProps->setDescription("Test document, generated by PHPExcel.");  
$objProps->setKeywords("office excel PHPExcel");  
$objProps->setCategory("Test");  
$objExcel->setActiveSheetIndex(0);  
  
  
$objActSheet = $objExcel->getActiveSheet();    
$objActSheet->setTitle('统计信息');  
  
//*************************************  
//设置单元格内容
//表头
$i=0;
$k1="商品名";
$k2="单价（元）";
$k3="数量";
$k4="单品总价（元）";
$k5="总价（元）";
$k6="单品百分比";  
$objActSheet->setCellValue('A1',$k1); 
$objActSheet->setCellValue('B1',$k2);
$objActSheet->setCellValue('C1',$k3); 
$objActSheet->setCellValue('D1',$k4);
$objActSheet->setCellValue('E1',$k5); 
$objActSheet->setCellValue('F1',$k6);

/////////////////////////////
while($row=$rs->fetchArray())
{   $ul=$i+2;
    $sql2=sprintf("select name,price from dishInfo where id=%d",$row['dish_id']);
    $rsName=$db->query($sql2) or die(ERR_SELECT_DB);
    $rowName=$rsName->fetchArray();
	$percentage=$row['sum(price*quantity)']/$total*100;
	$percentage=number_format($percentage,2);
	$objActSheet->setCellValue('A'.$ul,$rowName['name']); 
    $objActSheet->setCellValue('B'.$ul,$rowName['price']);
    $objActSheet->setCellValue('C'.$ul,$row['sum(quantity)']); 
    $objActSheet->setCellValue('D'.$ul,$row['sum(price*quantity)']);
    $objActSheet->setCellValue('E'.$ul,$total); 
    $objActSheet->setCellValue('F'.$ul,$percentage."%");
	$i++;
}
$db->close();
$db=null;
///////////////////////////////////
$objActSheet->getColumnDimension('A')->setWidth(15);
$objActSheet->getColumnDimension('B')->setWidth(15);  
$objActSheet->getColumnDimension('C')->setWidth(15);  
$objActSheet->getColumnDimension('D')->setWidth(15);  
$objActSheet->getColumnDimension('E')->setWidth(15);  
$objActSheet->getColumnDimension('F')->setWidth(15);  
$objActSheet->getColumnDimension('G')->setWidth(15);  
$outputFileName = "statistics.xls";  
header("Content-Type: application/force-download");  
header("Content-Type: application/octet-stream");  
header("Content-Type: application/download");  
header('Content-Disposition:inline;filename="'.$outputFileName.'"');  
header("Content-Transfer-Encoding: binary");  
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");  
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");  
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");  
header("Pragma: no-cache");  
$objWriter->save('php://output'); 
?>  

